_In sample.py:_  
**8 warning(s) found, 4 certain exceptions**  
At line 3: **possible** _TypeError_ exception of _Type 1_. Dangerous operation `**`.  
At line 4: **certain** _TypeError_ exception of _Type 1_. Dangerous operation `**`.  
At line 8: **possible** _TypeError_ exception of _Type 1_. Dangerous operation `%=`.  
At line 9: **certain** _TypeError_ exception of _Type 1_. Dangerous operation `<<=`.  
At line 13: **possible** _TypeError_ exception of _Type 1_. Dangerous operation `>=`.  
At line 14: **certain** _TypeError_ exception of _Type 1_. Dangerous operation `in`.  
At line 23: **possible** _TypeError_ exception of _Type 1_. Dangerous operation `*`.  
At line 24: **certain** _TypeError_ exception of _Type 1_. Dangerous operation `<<`.  

_In sample2.py:_  
**13 warning(s) found, 2 certain exceptions**  
At line 15: **possible** _TypeError_ exception of _Type 1_. Dangerous operation `x must be iterable`.  
At line 18: **certain** _TypeError_ exception of _Type 1_. Dangerous operation `1 must be iterable`.  

