_In sample.py:_
**9 warning(s) found, 0 certain exceptions**
At line 2: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '+='.
At line 3: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '%='.
At line 4: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<<='.
At line 7: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<'.
At line 8: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '>='.
At line 9: **possible** _TypeError_ exception of _Type 1_. Dangerous operation 'in'.
At line 17: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '+'.
At line 18: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '*'.
At line 19: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<<'.

_In sample2.py:_
**15 warning(s) found, 0 certain exceptions**
At line 2: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 3: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 4: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 7: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 8: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 9: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 12: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '[1,2]'.
At line 13: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 15: **possible** _TypeError_ exception of _Type 1_. Dangerous operation 'x'.
At line 16: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 18: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '1'.
At line 19: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 22: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 25: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 27: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.

