_In sample.py:_
**24 warning(s) found, 0 certain exceptions**
At line 2: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '+='.
At line 3: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '%='.
At line 4: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<<='.
At line 7: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<'.
At line 8: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '>='.
At line 9: **possible** _TypeError_ exception of _Type 1_. Dangerous operation 'in'.
At line 17: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '+'.
At line 18: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '*'.
At line 19: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '<<'.
At line 22: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 23: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 24: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 27: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 28: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 29: **possible** _TypeError_ exception of _Type 2_. Array index may not be an integer.
At line 32: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '[1,2]'.
At line 33: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 35: **possible** _TypeError_ exception of _Type 1_. Dangerous operation 'x'.
At line 36: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 38: **possible** _TypeError_ exception of _Type 1_. Dangerous operation '1'.
At line 39: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 42: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
At line 45: **possible** _TypeError_ exception of _Type 3_. Function print() may not take given number of arguments.
At line 47: **possible** _TypeError_ exception of _Type 3_. Function len() may not take given number of arguments.
